import Head from 'next/head'
import React from 'react'
import BreadsCrumb from '../../../components/BreadsCrumb'
import Layout from '../../../components/Layout'
import { useState } from 'react'
import ModalAccount from '../../../components/Modals/ModalAccount'

export default function index() {
    const [toggle, setToggle] = useState<boolean>(false)
    const [keys, setKeys] = useState<string>()
    const [toggleData, setToggleData] = useState<any>()

    const Page = [
        {
            label: 'Akun Pengguna',
            current: true,
        }
    ]
    return (
        <div>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={''} />
                <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet"></link>
            </Head>
            <Layout>
                <div>
                    <div>
                        <h3>Akun Pengguna</h3>
                    </div>
                    <div className='pt-5 pb-2'>
                        <button onClick={() => {
                            setToggle(!toggle)
                            setKeys('create')
                            setToggleData(null)
                        }} className='btn btn-primary'>
                            Tambah Akun
                        </button>
                    </div>

                    <table className='table table-stripper'>
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Email</th>
                                <th>No Telepon</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>Hilmi</td>
                                <td>hilmi@gmail.com</td>
                                <td>085700330044</td>
                                <td>Admin</td>
                                <td>
                                    <a href='#edit' onClick={() => {
                                        setToggle(!toggle)
                                        setKeys('update')
                                        setToggleData('')
                                    }} className='text-success'>Edit</a>
                                    <a href='#delete' className='text-danger ms-4'>Hapus</a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <ModalAccount toggle={toggle} setToggle={setToggle} keys={keys} />
                </div>
            </Layout>
        </div>
    )
}
