import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { bestprice, customerreview, customerservice, deliverytime, landing, quality } from '../assets'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {

  const provides = [
    {
      id: 1,
      title: 'High Quality Material',
      icon: quality
    },
    {
      id: 2,
      title: 'On Time Delivery',
      icon: deliverytime
    },
    {
      id: 3,
      title: 'Competitive Price',
      icon: bestprice
    },
    {
      id: 4,
      title: 'Excelent Services & Solution',
      icon: customerservice
    },
    {
      id: 5,
      title: 'Sourcing The Product That Customers Need',
      icon: customerreview
    },
  ]

  const [count, setCount] = useState(0)

  useEffect(() => {

  }, [count])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={''} />
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet"></link>
      </Head>
      <div>
        <div className='bg-landing'>
          <Navbar></Navbar>
          {/* <div className='bg-pink'>

          </div> */}
        </div>
        <div className='bg-default'>
          <h1 className='text-center'>Products Gallery</h1>
          <div className='d-flex justify-content-between px-5'>
            {
              [{ name: "Food Materials" }, { name: "Chemical Product" }, { name: "Cosmetic Ingredients" }]?.map((v: any) => (
                <div key={v}>
                  <div className='box' />
                  <p className='text-center'>{v?.name?.toUpperCase()}</p>
                </div>
              ))
            }
          </div>
        </div>

        {/* Info */}
        <div id='info' className='bg-default'>
          <p className='text-center' style={{ fontSize: 30 }}>
            <strong>PT. Multiverese Anugerah Chemindo</strong> is a company withhigh expertise in
            importing & distributing raw materials for cosmetic, food, and chemical industries.
          </p>
          <p className='text-center text-purple'>We Provide :</p>
          <div className='py-5'>
            <div className='d-flex justify-content-center gap-3'>
              {
                provides?.filter((v: any, i: number) => i < 3)?.map((val: any) => (
                  <div key={i} className='box-provide'>
                    <div style={{ marginTop: -30 }}>
                      <Image alt='v' src={val?.icon} width={70} height={70} />
                    </div>
                    <p className='fs-5'>{val?.title}</p>
                  </div>
                ))
              }
            </div>
            <div className='d-flex justify-content-center gap-3'>
              {
                provides?.filter((v: any, i: number) => i > 2)?.map((val: any) => (
                  <div key={i} className='box-provide'>
                    <div style={{ marginTop: -30 }}>
                      <Image alt='v' src={val?.icon} width={70} height={70} />
                    </div>
                    <p className='fs-5'>{val?.title}</p>
                  </div>
                ))
              }
            </div>
          </div>
        </div>

        {/* Testimonial */}
        <div id='testi' className='bg-default'>
          <div className='d-flex justify-content-between gap-5'>
            <div>
              <p className='fs-5 fw-bold'>Testimonial</p>
              <h2>
                What Customer Say About Us.
              </h2>
              <div className='d-flex justify-content-center gap-3' style={{ marginTop: 100 }}>
                {
                  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]?.map((v: any) => <div key={v} className='dotted' />)
                }
              </div>
            </div>
            <div>
              <div className='box-testi'>
                <p className='text-slide'>{provides[count]?.title}</p>
              </div>
            </div>
            <div>
              <button className='btn btn-primary' onClick={() => {
                if (count < provides?.length-1) {
                  setCount(count + 1)
                  console.log(count, 'countes')
                  return 
                } else {
                  setCount(0)
                }
              }}>Next</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
