import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { Form } from 'react-bootstrap'
import { alcohol, bestprice, brand, charcoal, customerreview, customerservice, deliverytime, indomap, landing, mail, panthenol, quality } from '../assets'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {

  const provides = [
    {
      id: 1,
      title: 'High Quality Material',
      icon: quality
    },
    {
      id: 2,
      title: 'On Time Delivery',
      icon: deliverytime
    },
    {
      id: 3,
      title: 'Competitive Price',
      icon: bestprice
    },
    {
      id: 4,
      title: 'Excelent Services & Solution',
      icon: customerservice
    },
    {
      id: 5,
      title: 'Sourcing The Product That Customers Need',
      icon: customerreview
    },
  ]

  const products = [
    {
      id: 1,
      title: 'Food Materials',
      image: panthenol
    },
    {
      id: 2,
      title: 'Chemical Product',
      image: alcohol
    },
    {
      id: 3,
      title: 'Cosmetic Ingredients',
      image: charcoal
    },
  ]

  const testimonials = [
    {
      id: 1,
      title: 'Fast respond, fast delivery, good quality materials',
      from: 'PT Lunar Mas'
    },
    {
      id: 2,
      title: 'Good quality and products',
      from: 'PT Ventura Apache'
    },
    {
      id: 3,
      title: 'The products was really nice',
      from: 'PT Abadi Lentera'
    },
  ]

  const [count, setCount] = useState(0)

  useEffect(() => {
  }, [count])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={''} />
        <link href="https://fonts.googleapis.com/css2?family=Abril+Fatface&display=swap" rel="stylesheet"></link>
      </Head>
      <div>
        <div className='bg-landing'>
          <Navbar></Navbar>
          <div className='bg-pink'>
            <Image src={brand} alt="brand" width={500} />

            <div className='container-pink'>
              <p className='text-purple2'>The Best Raw Material You Can Get!</p>
              <h1>
                Importers & Distributors
                <br />
                In The Chemical Industries
              </h1>
              <p className='fs-4'>
                Provide our customers with the best chemical <br />
                products at the best possible market price <br />
                without compromising quality.
              </p>
            </div>
          </div>
        </div>
        <div className='bg-default' id="product">
          <h1 className='text-center'>Products Gallery</h1>
          <div className='d-flex justify-content-between px-5'>
            {
              products?.map((v: any) => (
                <div key={v}>
                  <div className='box'>
                    <Image style={{ borderRadius: '20px' }} src={v?.image} alt="products" width={300} height={200} />
                  </div>
                  <p className='text-center fs-5 fw-bold mt-2'>{v?.title?.toUpperCase()}</p>
                </div>
              ))
            }
          </div>
        </div>

        {/* Info */}
        <div id='about' className='bg-default'>
          <p className='text-center' style={{ fontSize: 30 }}>
            <strong>PT. Multiverese Anugerah Chemindo</strong> is a company withhigh expertise in
            importing & distributing raw materials for cosmetic, food, and chemical industries.
          </p>
          <p className='text-center text-purple'>We Provide :</p>
          <div className='py-5'>
            <div className='d-flex justify-content-center gap-3'>
              {
                provides?.filter((v: any, i: number) => i < 3)?.map((val: any) => (
                  <div key={val} className='box-provide'>
                    <div style={{ marginTop: -30 }}>
                      <Image alt='v' src={val?.icon} width={70} height={70} />
                    </div>
                    <p className='fs-5'>{val?.title}</p>
                  </div>
                ))
              }
            </div>
            <div className='d-flex justify-content-center gap-3'>
              {
                provides?.filter((v: any, i: number) => i > 2)?.map((val: any) => (
                  <div key={val} className='box-provide'>
                    <div style={{ marginTop: -30 }}>
                      <Image alt='v' src={val?.icon} width={70} height={70} />
                    </div>
                    <p className='fs-5'>{val?.title}</p>
                  </div>
                ))
              }
            </div>
          </div>
        </div>

        {/* Vission & Mission */}
        <div className='bg-default'>
          <div className='d-flex flex-column align-items-center'>
            <div className='box-title'>
              <h5 className='text-center text-white'>Our Vision & Mission</h5>
            </div>
            <div className='box-vm mt-3'>
              <p className='text-center px-2'>
                Recognized as the leader of chemical raw materials distribution
                industry by all related industry players.
              </p>
            </div>
            <div className='d-flex flex-row justify-content-around gap-5'>
              <div className='box-vm mt-3'>
                <p className='text-center px-2'>
                  Deliver superior quality chemical products that contribute
                  positive impact to our customer`s business growth.
                </p>
              </div>
              <div className='box-vm mt-3'>
                <p className='text-center px-2'>
                  Forging meaningful, lifelong engagement and partnership with our
                  customer through customer centric offer.
                </p>
              </div>
            </div>
          </div>
          <h5 className='mt-4 text-center'>We supply on a nationwide</h5>
          <div className='d-flex justify-content-center'>
            <Image alt='maps' src={indomap} />
          </div>
        </div>

        {/* Testimonial */}
        <div id='testi' className='bg-default'>
          <div className='d-flex justify-content-between gap-5'>
            <div>
              <p className='fs-5 fw-bold'>Testimonial</p>
              <h2>
                What Customer Say <br />About Us.
              </h2>
              <div className='d-flex justify-content-center gap-3' style={{ marginTop: 100 }}>
                {
                  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]?.map((v: any) => <div key={v} className='dotted' />)
                }
              </div>
            </div>
            <div>
              <div className='box-testi'>
                <p className='text-slide'>{testimonials[count]?.title}</p>
                <p className='text-slide'>{testimonials[count]?.from}</p>
                <div className='d-flex justify-content-around'>
                  <div></div>
                  {/* <a className='text-primary' href='#previous' onClick={() => {
                    if (count < testimonials?.length - 1) {
                      setCount(count - 1)
                      console.log(count, 'countes')
                      return
                    }
                    else if (count < 0) {
                      setCount(0)
                      return
                    }
                  }}>
                    Previous
                  </a> */}
                  <a className='text-primary' href='#next' onClick={() => {
                    if (count < testimonials?.length - 1) {
                      setCount(count + 1)
                      console.log(count, 'countes')
                      return
                    } else {
                      setCount(0)
                    }
                  }}>
                    Next
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Mailing */}
        <div className='position-mail'>
          <Image alt='mails' src={mail} className='z-7' width={100} height={80} />
        </div>
        <div className='d-flex justify-content-center'>
          <div className='box-mailing'>
            <div>
              <Form>
                <input className='form-control' placeholder='Enter your name' required />
                <input className='form-control mt-2' placeholder='Enter company' required />
                <input className='form-control mt-2' placeholder='Enter phone number' required />
                <input className='form-control mt-2' placeholder='Enter email' type={'email'} required />
                <textarea className='form-control mt-2' placeholder='Enter message' required />
                <button className='btn btn-warning mt-2 w-100 text-white'>
                  Connect
                </button>
              </Form>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className='bg-default'>
        <div>
          <h2>Connect With Us!</h2>
        </div>
      </div>
    </div>
  )
}
